- name: Deploy NFS PV
  import_tasks: deploy_nfs.yml
  when: ocp4_aio_deploy_type == 'upi' or ocp4_aio_deploy_type == 'ipi'

- name: Deploy NFS PVs on rhacm SNO Cluster
  import_tasks: deploy_nfs_sno.yml
  when: ocp4_aio_deploy_type == 'sno'